import pprint
import numpy as np
import nwops

top=np.zeros(30,dtype=np.int32)
lens=np.ones(30,dtype=np.float64)

seq1= 'ATGGCTATTGTTAAATGTAAGCCGACTTCGGCTGGTCGCCGTCACGTCGTTAAAATTGTGAACAATGACCTGCATAAAGGTAAGCCTTATGCGCC' + \
      'GCTTTTAGAAAAAAATTCTAAAAACGGTGGTCGTAACAACAACGGTCGTATCACAGTACGTCACATCGGTGGTGGGCATAAGCAACACTATCGTT' + \
      'TGATCGATTTTAAACGTACTAAAGATGGCATTCCGGCAAAAGTTGAGCGTCTGGAATATGATCCAAACCGTAGTGCAAACATCGCTTTGGTTCTT' + \
      'TATGCAGACGGTGAACGTCGTTACATCATTGCACCGAAAGGTCTGCAAGCTGGTGATGTAATCCAGTCTGGCGTTGACGCACCGATTAAAGCAGG' + \
      'TAATACACTGCCGATGCGCAATATCCCAGTGGGTTCAACAGTTCACTGTGTTGAATTGAAACCTGGCAAAGGTGCACAACTTGCACGTTCTGCTG' + \
      'GTGCTTATGCACAAATCGTTGCTCGTGACGGTGCATACGCAACAATTCGTCTGCGTTCTGGTGAGATGCGTCGAGTTCCTTCTGAAGGTCGTGCA' + \
      'ACGATTGGTGAAGTTGGTAACTCTGAGCACATGCTTCGTGAACTTGGTAAAGCAGGTGCTACACGTTGGCGTGGTGTTCGTCCTACTGTTCGCGG' + \
      'TGTTGTGATGAACCCAGTTGACCACCCACACGGTGGTGGTGAAGGTCGCACATCCGGTGGTCGTCACCCTGTATCTCCTTGGGGTATGCCTACTA' + \
      'AGGGCTTCAAAACCCGTAAAAACAAACGCACCGACAAGTACATTGTACGTCGTCGTAATAAGTAA'
len(seq1) #825

seq2= 'TGGGGCCTTATTGTTTAAATATGTGTAAAGCCCCGCGGACACTCTTTTCTCGCGGGGCTGGTCCGCGCCCCCGTCACCGTCTCGTTAAAATTTGTG' + \
      'AACAAAAATGACACCCCTCTGTGCGCACATAAAAAGGTAAGCCTCTTATATTGCGCCGCTCTTTTTTTTTTATAGAGAGAAAAAAATTCTAAAAAA' + \
      'AAACACGCGGGGTGTGTGGGGTTCGTATAAACACAACAACGGTCGTATATCACAGTACCGTCTCAACATCGGGTGGTGTGGGGGGGCATAAGCAAC' + \
      'ACACTATATCGTTTTTGATCGCGATTTTTTTTAAACGTACTAAAAAAGATGGCGCACATTCTCCGCGGGGCAAAAAAGAGTGTTTTGTGAGAGCGC' + \
      'GTGTCTCTGGGGAGAAAATATATGTGAGATCCCAAACCCGTGTATAGTGTGTGCGCACAAAAACACATATCTCGCGGCT'
len(seq2) #463

Fmat=np.zeros((len(seq1) + 1, len(seq2) + 1), dtype=np.int32)
Dmat=np.zeros((len(seq1) + 1, len(seq2) + 1), dtype=np.int32)

a = nwops.get_pairwise_alignment(seq1, seq2, Fmat, Dmat)
pprint.pprint(a)


# b = nwops.get_pairwise_alignment_test(seq1, seq2, Fmat, Dmat)

